[project]
name = "coral-prompted-seg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "coral-schemas",
    "fastapi[standard]>=0.116.2",
    "hydra-core>=1.3.2",
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
    "sam2>=1.1.0",
    "transformers>=4.57.1",
]

[tool.uv.sources]
coral-schemas = { git = "https://github.com/yapat-app/coral-schemas.git" }
