[project]
name = "coral-prompted-seg"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "coral-schemas",
    "fastapi[standard]>=0.116.2",
    "hydra-core>=1.3.2",
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
    "sam2>=1.1.0",
    "transformers>=4.57.1",
]

[tool.uv.sources]
coral-schemas = { git = "ssh://git@github.com/yapat-app/coral-schemas.git" }
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
]

[project.optional-dependencies]
# Define your hardware-specific "flavors"
cpu = [
    "torch",
    "torchvision",
    "torchaudio",
]
cuda = [
    "torch",
    "torchvision",
    "torchaudio",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
